import {
    MARTA_REWARD_FAIL,
    MARTA_REWARD_SUCCESS,
    MARTA_QUEST_XP_LEVEL_2_THRESHOLD,
    type CombatOutcome,
    type MartaQuestFlow,
    type MartaQuestScenario,
    type QuestLine,
    type RewardResolution,
} from 'shared';

export const OLD_MARTA_NPC_ID = '10000000-0000-4000-a000-000000000002';
export const GRIM_ALDRIC_NPC_ID = '10000000-0000-4000-a000-000000000001';
export const GUARD_THERON_NPC_ID = '10000000-0000-4000-a000-000000000003';
export const TAVERN_CELLAR_LOCATION_ID = '00000000-0000-4000-a000-000000000010';

export function buildMartaScenario(seed: number = Date.now()): MartaQuestScenario {
    const variants = [
        {
            title: 'Bones Beneath the Casks',
            synopsis: 'Old Marta saw bone-dust trails under the tavern cellar. Something keeps opening a sealed hatch.',
            combatStage: 'Descend into the cellar and defeat the Bone-Rat Pack guarding the hatch.',
        },
        {
            title: 'The Ashen Ledger',
            synopsis: 'A cursed ledger vanished from the tavern archives. Marta wants it back before moonrise.',
            combatStage: 'Track the thief to the alley shrine and defeat the Hollow Collector.',
        },
        {
            title: 'Whisper in the Barrel Room',
            synopsis: 'Marta hears a whisper from old casks every third bell. She fears a spirit anchor.',
            combatStage: 'Break the anchor by defeating the Whispered Warden in close quarters.',
        },
    ];
    const variant = variants[Math.abs(seed) % variants.length];

    return {
        title: variant.title,
        synopsis: variant.synopsis,
        steps: [
            {
                step: 'talk_to_marta',
                title: 'Speak with Old Marta',
                description: 'Receive the prophecy-task and confirm readiness.',
                mandatory: true,
            },
            {
                step: 'accept_and_prepay',
                title: 'Activate Adventure',
                description: 'Lock the adventure prepay and initialize dicepack.',
                mandatory: true,
            },
            {
                step: 'complete_adventure',
                title: 'Follow Marta Clue',
                description: 'Investigate the objective trail generated by the server.',
                mandatory: true,
            },
            {
                step: 'combat_mandatory',
                title: 'Mandatory Combat',
                description: variant.combatStage,
                mandatory: true,
            },
            {
                step: 'return_to_marta',
                title: 'Return to Marta',
                description: 'Report combat outcome and await judgement.',
                mandatory: true,
            },
            {
                step: 'turn_in',
                title: 'Turn-in and Resolve Reward',
                description: 'GM d20 decides NFT reward eligibility on success.',
                mandatory: true,
            },
        ],
    };
}

export function buildInitialMartaFlow(seed: number = Date.now()): MartaQuestFlow {
    return {
        questLine: 'marta',
        state: 'OFFERED_BY_MARTA',
        branch: 'pending',
        combatOutcome: null,
        scenario: buildMartaScenario(seed),
        questGiverNpcId: OLD_MARTA_NPC_ID,
        sessionId: null,
        rewardResolution: null,
        rewardDraft: null,
        metadata: {},
    };
}

export function buildAldricScenario(): MartaQuestScenario {
    return {
        title: 'Rats In The Cellar',
        synopsis: 'Grim Aldric is furious: cellar rats keep devouring tavern supplies.',
        steps: [
            {
                step: 'talk_to_aldric',
                title: 'Speak with Grim Aldric',
                description: 'Hear his request to clear the cellar rat threat.',
                mandatory: true,
            },
            {
                step: 'accept_and_prepay',
                title: 'Accept and Prepay',
                description: 'Activate the contract and open the cellar route.',
                mandatory: true,
            },
            {
                step: 'combat_mandatory',
                title: 'Kill the Cellar Rat',
                description: 'Enter the cellar and defeat the quest rat in turn-based combat.',
                mandatory: true,
            },
            {
                step: 'return_to_aldric',
                title: 'Return to Aldric',
                description: 'Report the result and claim your pay.',
                mandatory: true,
            },
            {
                step: 'turn_in',
                title: 'Turn in quest',
                description: 'On success, NFT reward is guaranteed.',
                mandatory: true,
            },
        ],
    };
}

export function buildInitialAldricFlow(seed: number = Date.now()): MartaQuestFlow {
    return {
        questLine: 'aldric',
        state: 'OFFERED_BY_ALDRIC',
        branch: 'pending',
        combatOutcome: null,
        scenario: buildAldricScenario(),
        questGiverNpcId: GRIM_ALDRIC_NPC_ID,
        sessionId: null,
        rewardResolution: null,
        rewardDraft: null,
        metadata: {
            cellarEntranceEnabled: false,
            cellarLocationId: TAVERN_CELLAR_LOCATION_ID,
            cellarCombatStarted: false,
            cellarCombatResolved: false,
            cellarCombatId: null,
            seed,
        },
    };
}

export function buildTheronScenario(): MartaQuestScenario {
    return {
        title: 'Watch Oath Trial',
        synopsis: 'Guard Theron tests your wit and nerve before granting a watch-sealed relic.',
        steps: [
            {
                step: 'talk_to_theron',
                title: 'Speak with Guard Theron',
                description: 'Ask for the watch trial.',
                mandatory: true,
            },
            {
                step: 'answer_theron_q1',
                title: 'Answer Question One',
                description: 'Choose the lawful answer to Theron\'s first question.',
                mandatory: true,
            },
            {
                step: 'answer_theron_q2',
                title: 'Answer Question Two',
                description: 'Choose the correct tactical answer.',
                mandatory: true,
            },
            {
                step: 'roll_d20',
                title: 'Roll D20',
                description: 'Roll a d20. A roll above 5 completes the trial.',
                mandatory: true,
            },
            {
                step: 'turn_in',
                title: 'Mint Watch Relic',
                description: 'On success, generate and mint an NFT relic.',
                mandatory: true,
            },
        ],
    };
}

export function buildInitialTheronFlow(seed: number = Date.now()): MartaQuestFlow {
    return {
        questLine: 'theron',
        state: 'OFFERED_BY_THERON',
        branch: 'pending',
        combatOutcome: null,
        scenario: buildTheronScenario(),
        questGiverNpcId: GUARD_THERON_NPC_ID,
        sessionId: null,
        rewardResolution: null,
        rewardDraft: null,
        metadata: {
            theronQuestionIndex: 0,
            theronCorrectAnswers: 0,
            theronRollRequired: false,
            theronRollResult: null,
            seed,
        },
    };
}

export function rollD20(rng: () => number = Math.random): number {
    return Math.floor(rng() * 20) + 1;
}

export function resolveRewardFromOutcome(
    questLine: QuestLine,
    combatOutcome: CombatOutcome,
    gmRoll: number,
): RewardResolution {
    if (questLine === 'aldric') {
        if (combatOutcome === 'success') {
            return {
                gmRoll: null,
                nftAwarded: true,
                rewardReason: 'guaranteed_success',
            };
        }
        return {
            gmRoll: null,
            nftAwarded: false,
            rewardReason: 'combat_failed',
        };
    }

    if (combatOutcome !== 'success') {
        return {
            gmRoll,
            nftAwarded: false,
            rewardReason: 'combat_failed',
        };
    }
    if (gmRoll >= 15) {
        return {
            gmRoll,
            nftAwarded: true,
            rewardReason: 'gm_roll_passed',
        };
    }
    return {
        gmRoll,
        nftAwarded: false,
        rewardReason: 'gm_roll_failed',
    };
}

export function computeQuestProgressDelta(combatOutcome: CombatOutcome, currentXp: number) {
    const reward = combatOutcome === 'success' ? MARTA_REWARD_SUCCESS : MARTA_REWARD_FAIL;
    const nextXp = Math.max(0, currentXp) + reward.xp;
    const levelDelta = currentXp < MARTA_QUEST_XP_LEVEL_2_THRESHOLD && nextXp >= MARTA_QUEST_XP_LEVEL_2_THRESHOLD ? 1 : 0;

    return {
        xpDelta: reward.xp,
        loreDelta: reward.lore,
        levelDelta,
        nextXp,
    };
}

export function buildRewardDraft(questId: string, gmRoll: number) {
    const rarityTier = gmRoll >= 19 ? 5 : gmRoll >= 17 ? 4 : 3;
    const rewardName =
        rarityTier >= 5
            ? 'Marta Prophecy Relic'
            : rarityTier >= 4
                ? 'Marta Oath Relic'
                : 'Marta Tavern Relic';

    return {
        name: rewardName,
        rarityTier,
        metadataCid: `marta-meta-${questId}-${gmRoll}`,
        loreCid: `marta-lore-${questId}-${Date.now()}`,
    };
}

export function buildAldricRewardDraft(questId: string) {
    return {
        name: 'Aldric Cellar Trophy',
        rarityTier: 4,
        metadataCid: `aldric-meta-${questId}-${Date.now()}`,
        loreCid: `aldric-lore-${questId}-${Date.now()}`,
    };
}

export function buildTheronRewardDraft(questId: string, roll: number) {
    const rarityTier = roll >= 18 ? 5 : roll >= 12 ? 4 : 3;
    return {
        name: 'Theron Watch Sigil',
        rarityTier,
        metadataCid: `theron-meta-${questId}-${roll}`,
        loreCid: `theron-lore-${questId}-${Date.now()}`,
    };
}
